sudo: required
language: generic

env:
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

services: 
  - docker

before_install:
  - echo "Decrypting service-account..."
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - echo "Installing Google Cloud SDK..."
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - echo "Login into Google Cloud..."
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project abiding-cycle-362117
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials codetogive-cluster
  - echo "Login into Docker..."
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_PASSWORD" --password-stdin
  - echo "Building test image..."
  - docker build -t vantoan11/server-test-image -f ./server/Dockerfile.dev ./server

script:
  - echo "Running tests using Pytest..."
  - docker run vantoan11/server-test-image poetry run pytest

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master