version: '3'
services:
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - ./server/server:/code/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
  wordpress:
    image: 'wordpress:latest'
    restart: always
    depends_on:
      - mysql
    ports:
      - '80:80'
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=mysql
      - WORDPRESS_DB_PASSWORD=mysql
      - WORDPRESS_DB_NAME=mysql
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
