version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./server/server:/server/server
      - ./server/migrations:/server/migrations
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_HOST=mysql
      - HOST_DOMAIN=http://localhost:80
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    restart: always
    volumes:
      - ./client/CodeToGive2022_Frontend:/client
      - /client/node_modules
    environment:
      - HOST=http://34.116.151.108
  wordpress:
    image: "wordpress:latest"
    restart: always
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=mysql
      - WORDPRESS_DB_PASSWORD=mysql
      - WORDPRESS_DB_NAME=mysql
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=password
  redis:
    image: "redis:latest"
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
