apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-volume-claim
  labels:
    component: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi