apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    component: wordpress
spec:
  selector:
    matchLabels:
      component: wordpress
  template:
    metadata:
      labels:
        component: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-cluster-ip-service
        - name: WORDPRESS_DB_USER
          value: mysql
        - name: WORDPRESS_DB_NAME
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD